[package]
name = "rust_hello_world"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"
bindgen = "0.59"

[dependencies]
#cc = "1.0"
#libc = "0.2.0"