/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    #[link_name = "\u{1}_Z5hellov"]
    pub fn hello();
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pleasework {
    pub a: ::std::os::raw::c_int,
    pub b: f32,
}
#[test]
fn bindgen_test_layout_pleasework() {
    assert_eq!(
        ::std::mem::size_of::<pleasework>(),
        8usize,
        concat!("Size of: ", stringify!(pleasework))
    );
    assert_eq!(
        ::std::mem::align_of::<pleasework>(),
        4usize,
        concat!("Alignment of ", stringify!(pleasework))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<pleasework>())).a as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(pleasework),
            "::",
            stringify!(a)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<pleasework>())).b as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(pleasework),
            "::",
            stringify!(b)
        )
    );
}
